<?php
// English language strings
return array(
    'home' => 'Home',
    'search' => 'FIND YOUR CLASSES HERE',
    'myclass' => 'My Classes',
    'classes' => 'Classes',
    'our-classes' => 'Our Classes',
    'teachers' => 'Teachers',
    'payment' => 'Payment',
    'exam' => 'Exams',
    'language' => 'Language',
    'help' => 'Help',
    'login' => 'Login',
    'register' => 'Register',
    'logout' => 'Logout',
    'student' => 'Student',
    'search-placeholder' => 'Search here...',
    'search-button' => 'Search',
    'load' => 'Load More',
    'become' => 'Become our family member',
    'become-t' => 'Become a teacher',
    'logged-in' => 'Successfully Logged in',
    'request-sent' => 'Request Sent',
    'request-failed' => 'Failed to send request!',
    'admin' => 'Our administrators will respond to your request soon as possible',
    'try-again' => 'Please try again',
    'banned' => 'You have been banned. Please check do you have unpaid fees. If is not, please contact administrator.',
    'requested' => 'You have already requested to join this class',
    'already-in' => 'You are already in this class',
    'change-VA-error' => 'Failed to Turn off Voice Assistant',
    'file-uploaded' => 'Your CV has uploaded successfully',
    'file-cv-ok' => 'Our administrators will contact you soon.',
);
?>
